-- Tabla de Órdenes de Mantenimiento
CREATE TABLE IF NOT EXISTS ordenes_mantenimiento (
    id_orden BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_orden TEXT UNIQUE NOT NULL,
    fecha_creacion DATE DEFAULT CURRENT_DATE,
    id_maquinaria BIGINT REFERENCES maquinarias(id_maquinaria),
    tipo_mantenimiento TEXT, -- Preventivo, Correctivo, etc
    prioridad TEXT, -- Baja, Media, Alta, Critica
    descripcion_fallo TEXT,
    sintomas TEXT,
    tecnico_responsable TEXT, -- Nombre o ID si existiera tabla tecnicos
    equipo_apoyo TEXT,
    fecha_inicio TIMESTAMP WITH TIME ZONE,
    fecha_fin_estimada TIMESTAMP WITH TIME ZONE,
    estado TEXT DEFAULT 'Pendiente', -- Pendiente, En Proceso, Completado
    repuestos JSONB DEFAULT '[]'::jsonb, -- Lista de repuestos usados
    actividades_procedimiento TEXT,
    metodos_seguridad TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Políticas RLS (Row Level Security)
ALTER TABLE ordenes_mantenimiento ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura autenticada" ON ordenes_mantenimiento
FOR SELECT USING (auth.role() = 'authenticated' OR auth.role() = 'anon');

CREATE POLICY "Permitir insercion autenticada" ON ordenes_mantenimiento
FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'anon');

CREATE POLICY "Permitir actualizacion autenticada" ON ordenes_mantenimiento
FOR UPDATE USING (auth.role() = 'authenticated' OR auth.role() = 'anon');
